sequenceDiagram
  box rgb(191, 223, 255) Alice & John
    participant Alice
    participant John
  end
  box Another Group
    actor Bob
    actor June
  end
  Alice->>John: Hello John, how are you?
  John->>Alice: Great!
  Alice->>Bob: Hello Bob, how is June?
  Bob->>June: Hello June, how are you?
