sequenceDiagram
  rect rgb(191, 223, 255)
  box rgb(252, 194, 215) Alice and John
    participant Alice
    actor John
  end
  note right of Alice: Alice calls John.
  Alice->>+John: Hello John, how are you?
  John-->>-Alice: I feel great!
  end
