/**
 * WebviewTemplate — builds the complete HTML document for the Accordo
 * Commentable Preview webview.
 *
 * The HTML document structure:
 *   - CSP <meta> with nonce (script-src and style-src)
 *   - KaTeX stylesheet (for math rendering — pre-rendered server-side but CSS still needed)
 *   - Mermaid.js script (for diagram rendering — runs client-side)
 *   - Comment SDK script (@accordo/comment-sdk)
 *   - Rendered markdown body (pre-rendered HTML fragment)
 *   - Initialization script (wires SDK, calls mermaid.initialize, sets up postMessage)
 *   - VS Code theme CSS variables via body style
 *
 * Source: M41b — WebviewTemplate
 *
 * Requirements:
 *   M41b-TPL-01  Returns a valid HTML document string
 *   M41b-TPL-02  CSP <meta> tag contains the provided nonce
 *   M41b-TPL-03  KaTeX CSS <link> tag present
 *   M41b-TPL-04  Mermaid <script> tag with nonce attribute
 *   M41b-TPL-05  SDK <script> tag with nonce attribute
 *   M41b-TPL-06  Rendered markdown body included in output
 *   M41b-TPL-07  Init script calls AccordoCommentSDK initialization
 *   M41b-TPL-08  Body uses VS Code CSS variable for background color
 */

// ── TemplateOptions ───────────────────────────────────────────────────────────

export interface TemplateOptions {
  /** Random nonce for CSP — generated by CommentablePreviewEditor per render */
  nonce: string;
  /** Pre-rendered markdown HTML fragment */
  body: string;
  /** URI string for the katex.min.css webview resource */
  katexCssUri: string;
  /** URI string for mermaid.min.js webview resource */
  mermaidJsUri: string;
  /** URI string for the compiled comment-sdk.js webview resource */
  sdkJsUri: string;
  /** URI string for the compiled comment-sdk.css webview resource */
  sdkCssUri: string;
  /**
   * VS Code theme kind (1=light, 2=dark, 3=hc-dark, 4=hc-light).
   * Used to set a class on <body> for theme-specific CSS overrides.
   */
  themeKind: 1 | 2 | 3 | 4;
  /**
   * VS Code webview CSP source string (e.g. `vscode-webview://...`).
   * Pass `webviewPanel.webview.cspSource` at call site.
   */
  cspSource: string;
  /**
   * Additional <script src="..."> URIs injected before </body>.
   * Used to extend with WaveDrom, Viz.js, Vega, Plotly, MathJax, etc.
   * The nonce is applied automatically to each tag.
   */
  additionalScripts?: string[];
  /**
   * Additional <link rel="stylesheet"> URIs injected in <head>.
   * Used to extend with MathJax CSS, Vega themes, etc.
   */
  additionalStylesheets?: string[];
}

// ── buildWebviewHtml ──────────────────────────────────────────────────────────

/**
 * M41b-TPL-01 through M41b-TPL-08
 * Build the full HTML document string for the preview webview.
 */
export function buildWebviewHtml(opts: TemplateOptions): string {
  const {
    nonce,
    body,
    katexCssUri,
    mermaidJsUri,
    sdkJsUri,
    sdkCssUri,
    themeKind,
    cspSource,
    additionalScripts = [],
    additionalStylesheets = [],
  } = opts;

  const bodyClass = themeKindToClass(themeKind);

  const extraLinks = additionalStylesheets
    .map((href) => `    <link rel="stylesheet" href="${href}">`)
    .join("\n");

  const extraScripts = additionalScripts
    .map((src) => `    <script nonce="${nonce}" src="${src}"></script>`)
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'nonce-${nonce}' ${cspSource}; style-src ${cspSource} 'unsafe-inline'; img-src ${cspSource} https: data:; font-src ${cspSource} data:; connect-src ${cspSource};">
  <link rel="stylesheet" href="${katexCssUri}">
  <link rel="stylesheet" href="${sdkCssUri}">
${extraLinks}
</head>
<body class="${bodyClass}">
${body}
  <script nonce="${nonce}" src="${mermaidJsUri}"></script>
  <script nonce="${nonce}" src="${sdkJsUri}"></script>
${extraScripts}
  <script nonce="${nonce}">
    (function () {
      const sdk = new AccordoCommentSDK();
      const vscode = acquireVsCodeApi();

      function coordinateToScreen(blockId) {
        const el = document.querySelector('[data-block-id="' + blockId + '"]');
        if (!el) return null;
        const rect = el.getBoundingClientRect();
        return { x: rect.right, y: rect.top };
      }

      try {
      sdk.init({
        container: document.body,
        coordinateToScreen,
        callbacks: {
          onCreate(blockId, body, intent) {
            vscode.postMessage({ type: 'comment:create', blockId, body, intent });
          },
          onReply(threadId, body) {
            vscode.postMessage({ type: 'comment:reply', threadId, body });
          },
          onResolve(threadId, resolutionNote) {
            vscode.postMessage({ type: 'comment:resolve', threadId, resolutionNote });
          },
          onReopen(threadId) {
            vscode.postMessage({ type: 'comment:reopen', threadId });
          },
          onDelete(threadId, commentId) {
            vscode.postMessage({ type: 'comment:delete', threadId, commentId });
          },
        },
      });
      } catch(e) { console.error('[accordo-preview] sdk.init() FAILED', e); }

      window.addEventListener('message', (event) => {
        const msg = event.data;
        if (msg.type === 'comments:load') {
          sdk.loadThreads(msg.threads);
        } else if (msg.type === 'comments:add') {
          sdk.addThread(msg.thread);
        } else if (msg.type === 'comments:update') {
          sdk.updateThread(msg.threadId, msg.update);
        } else if (msg.type === 'comments:remove') {
          sdk.removeThread(msg.threadId);
        } else if (msg.type === 'comments:focus') {
          sdk.openPopover(msg.threadId);
        }
      });

      mermaid.initialize({ startOnLoad: true });
    })();
  </script>
</body>
</html>`;
}

// ── Theme class helper (exported for testing) ─────────────────────────────────

/**
 * Returns the CSS body class for a VS Code theme kind.
 *   1 → "vscode-light"
 *   2 → "vscode-dark"
 *   3 → "vscode-high-contrast"
 *   4 → "vscode-high-contrast-light"
 */
export function themeKindToClass(kind: 1 | 2 | 3 | 4): string {
  const map: Record<1 | 2 | 3 | 4, string> = {
    1: "vscode-light",
    2: "vscode-dark",
    3: "vscode-high-contrast",
    4: "vscode-high-contrast-light",
  };
  return map[kind] ?? "vscode-dark";
}
