/**
 * A16 — Webview HTML builder for the Excalidraw diagram canvas webview.
 *
 * Mirrors the md-viewer webview-template.ts pattern:
 *   - Nonce-based CSP (Content Security Policy)
 *   - Single bundle script tag
 *   - Minimal DOM: one #excalidraw-root div
 *
 * No VSCode import — this module is usable in Node.js tests without any
 * VSCode mocks.
 *
 * CSP note: style-src requires 'unsafe-inline' because Excalidraw's React
 * renderer injects inline styles at runtime. script-src uses nonce + cspSource
 * for the bundle; data:/blob: img-src is required for Excalidraw's SVG export.
 *
 * Source: diag_workplan.md §4.16 / diag_arch_v4.2.md §9.4
 *
 * Requirements:
 *   WH-01  Returns a valid HTML document string (<!DOCTYPE html>)
 *   WH-02  CSP <meta> tag contains nonce-{nonce}
 *   WH-03  CSP <meta> tag contains cspSource
 *   WH-04  Contains <div id="excalidraw-root">
 *   WH-05  <script> tag has nonce="{nonce}" and src="{bundleUri}"
 *   WH-06  style-src contains 'unsafe-inline'
 */

// ── HtmlOptions ───────────────────────────────────────────────────────────────

export interface HtmlOptions {
  /**
   * Random nonce for CSP — generate with randomBytes(16).toString("hex").
   * Generated by panel.ts per-render so it is never reused.
   */
  nonce: string;
  /**
   * VSCode webview CSP source string.
   * Pass `webviewPanel.webview.cspSource` at the call site.
   */
  cspSource: string;
  /**
   * Webview URI for the compiled webview bundle.
   * Derive with panel.webview.asWebviewUri(Uri.joinPath(extensionUri, "dist/webview/webview.bundle.js")).toString()
   */
  bundleUri: string;
  /**
   * Optional VS Code webview URI string for Virgil.woff2.
   * When provided, an @font-face rule is injected so the hand-drawn Excalidraw
   * font loads correctly inside the webview's restricted CSP environment.
   * Use panel.webview.asWebviewUri(Uri.joinPath(extensionUri, "dist", "webview", "Virgil.woff2"))
   */
  virgilFontUri?: string;
  /**
   * Optional VS Code webview URI string for the directory that *contains*
   * the excalidraw-assets folder (i.e. dist/webview/, not dist/webview/excalidraw-assets/).
   * When provided, window.EXCALIDRAW_ASSET_PATH is set so Excalidraw's webpack
   * runtime loads its vendor chunk from the local extension dist folder instead
   * of the default https://unpkg.com CDN, which is blocked by CSP.
   * Use panel.webview.asWebviewUri(Uri.joinPath(extensionUri, "dist", "webview"))
   */
  excalidrawAssetsUri?: string;
}

// ── getWebviewHtml ─────────────────────────────────────────────────────────────

/**
 * WH-01 through WH-06
 * Build the full HTML document for the Excalidraw canvas webview.
 */
export function getWebviewHtml(opts: HtmlOptions): string {
  const { nonce, cspSource, bundleUri, virgilFontUri, excalidrawAssetsUri } = opts;
  // Make the font URI available to webview.ts module-level code via a global.
  // webview.ts injects the @font-face rule via JS AFTER Excalidraw's bundle CSS
  // has already run, so our rule wins the CSS cascade over Excalidraw's rule for
  // the same font-family name.
  const virgilGlobal = virgilFontUri ? `\n  window.__virgilFontUri = "${virgilFontUri}";` : "";
  // Trailing slash is required — webpack public path must end with /
  const assetPathGlobal = excalidrawAssetsUri ? `\n  window.EXCALIDRAW_ASSET_PATH = "${excalidrawAssetsUri}/";` : "";
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'nonce-${nonce}' ${cspSource}; style-src ${cspSource} 'unsafe-inline'; img-src data: blob: ${cspSource}; font-src ${cspSource} data:; connect-src ${cspSource}; worker-src blob:;">
  <style>html,body,#excalidraw-root{margin:0;padding:0;height:100%;width:100%;overflow:hidden;}</style>
</head>
<body>
  <div id="excalidraw-root"></div>
  <script nonce="${nonce}">
    // Buffer JS errors that occur before the bundle acquires the VS Code API.
    // The bundle reads window.__accordoErrors after acquireVsCodeApi() and flushes them.
    window.__accordoErrors = [];
    window.onerror = function(msg, src, line) {
      window.__accordoErrors.push(String(msg) + ' (' + src + ':' + line + ')');
    };
    window.addEventListener('unhandledrejection', function(ev) {
      window.__accordoErrors.push('UnhandledRejection: ' + String(ev.reason));
    });${assetPathGlobal}${virgilGlobal}
  </script>
  <script nonce="${nonce}" src="${bundleUri}"></script>
</body>
</html>`;
}
